"""
Alert and Model Registry models.
"""
import uuid

from django.contrib.postgres.fields import ArrayField
from django.db import models


class Alert(models.Model):
    """Security alert generated by the ML detection engine."""

    SEVERITY_CHOICES = [
        ("LOW", "Low"),
        ("MEDIUM", "Medium"),
        ("HIGH", "High"),
        ("CRITICAL", "Critical"),
    ]

    STATUS_CHOICES = [
        ("OPEN", "Open"),
        ("ACKNOWLEDGED", "Acknowledged"),
        ("RESOLVED", "Resolved"),
    ]

    ALERT_TYPE_CHOICES = [
        ("port_scan", "Port Scan"),
        ("brute_force", "Brute Force"),
        ("ddos", "DDoS"),
        ("exfiltration", "Data Exfiltration"),
        ("web_attack", "Web Attack"),
        ("infiltration", "Infiltration"),
        ("bot", "Bot Activity"),
        ("dos_slowloris", "DoS Slowloris"),
        ("dos_hulk", "DoS Hulk"),
        ("heartbleed", "Heartbleed"),
        ("anomaly", "General Anomaly"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, db_index=True)
    alert_type = models.CharField(max_length=100, choices=ALERT_TYPE_CHOICES, db_index=True)
    source_ip = models.GenericIPAddressField(db_index=True)
    destination_ip = models.GenericIPAddressField(null=True, blank=True)
    anomaly_score = models.FloatField(default=0.0)
    model_used = models.CharField(max_length=50, default="ensemble")
    description = models.TextField(blank=True, default="")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="OPEN", db_index=True)
    acknowledged_by = models.CharField(max_length=100, blank=True, default="")
    resolved_at = models.DateTimeField(null=True, blank=True)
    raw_log_ids = ArrayField(models.UUIDField(), default=list, blank=True)
    confidence = models.FloatField(default=0.0)
    predicted_label = models.CharField(max_length=50, blank=True, default="")

    class Meta:
        db_table = "alerts"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["severity", "created_at"], name="idx_alerts_sev_ts"),
            models.Index(fields=["status"], name="idx_alerts_status"),
            models.Index(fields=["alert_type"], name="idx_alerts_type"),
        ]

    def __str__(self):
        return f"[{self.severity}] {self.alert_type} from {self.source_ip}"


class ModelRegistry(models.Model):
    """Trained ML model metadata — tracks versions, metrics, and active status."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    model_name = models.CharField(max_length=100)
    version = models.CharField(max_length=20)
    algorithm = models.CharField(max_length=50)
    dataset_trained_on = models.CharField(max_length=100, default="CICIDS2017")
    f1_score = models.FloatField(default=0.0)
    precision_score = models.FloatField(default=0.0)
    recall_score = models.FloatField(default=0.0)
    roc_auc = models.FloatField(default=0.0)
    training_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)
    mlflow_run_id = models.CharField(max_length=100, blank=True, default="")
    artifact_path = models.TextField(blank=True, default="")

    class Meta:
        db_table = "model_registry"
        ordering = ["-training_date"]
        unique_together = ["model_name", "version"]

    def __str__(self):
        active = "✓" if self.is_active else "✗"
        return f"{self.model_name} v{self.version} [{active}] F1={self.f1_score:.3f}"
